#!/bin/sh
set -e
case "$1" in
    configure)
        systemctl daemon-reload 2>/dev/null || true
        if systemctl is-enabled node-red >/dev/null 2>&1; then
            systemctl try-restart node-red 2>/dev/null || true
        fi
        ;;
esac
#DEBHELPER#
exit 0
